language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "docbook-xsl xsltproc yast2-core-dev yast2-devtools libxcrypt-dev cmake yast2-ycp-ui-bindings-dev ruby2.1 ruby2.1-dev rake ruby-fast-gettext language-pack-en language-pack-cs screen" -g "yast-rake rspec:3.3.0 rubocop:0.41.2"
script:
    - rake check:syntax
    - rubocop
    # TODO FIXME: hack for Travis build, cmake includes "/usr/include/ruby-2.1.0/x86_64-linux-gnu"
    # instead of "/usr/include/x86_64-linux-gnu/ruby-2.1.0"
    - export CXXFLAGS=-I/usr/include/x86_64-linux-gnu/ruby-2.1.0
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB=lib -DCMAKE_VERBOSE_MAKEFILE=ON
    - make -j 4
    - sudo make install
    - (cd tests/ruby && make test ARGS=-V)

